name: Build & publish Docker image

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push docker to GitHub registry
      - name: Build and push container for ubuntu-jdk-android-latest
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./containers/ubuntu-jdk-android-latest
          tags: ghcr.io/${{ github.actor }}/containers/ubnutu-jdk17-android34:latest
